<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>ScumFreeBot</AssemblyName>
    <RootNamespace>ScumFreeBot</RootNamespace>
	<Version>0.6.21</Version>
	<AssemblyVersion>0.6.21.0</AssemblyVersion>
	<FileVersion>0.6.21.0</FileVersion>
	<InformationalVersion>0.6.21</InformationalVersion>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="SSH.NET" Version="2024.1.0" />
		<PackageReference Include="FluentFTP" Version="52.0.0" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Data\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Assets\" />
	</ItemGroup>
	<ItemGroup>
		<Resource Include="Assets\logo.png" />
	</ItemGroup>
</Project>
